name: 3DModel
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - bleach=6.3.0=py311haa95532_0
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - git=2.51.0=haa95532_1
  - h11=0.16.0=py311haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=py311haa95532_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=pyh29332c3_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - python_abi=3.11=2_cp311
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qtconsole=5.7.0=py311haa95532_0
  - qtpy=2.4.3=py311haa95532_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=py311haa95532_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - arrow==1.4.0
      - beautifulsoup4==4.14.3
      - black==25.11.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.73.0
      - docker==7.1.0
      - fastapi==0.123.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.61.0
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - huey==2.5.4
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - joblib==1.5.2
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyterlab==4.5.0
      - jupyterlab-widgets==3.0.16
      - kaggle==1.8.2
      - kagglesdk==0.1.13
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazypredict==0.2.16
      - learn==1.0.0
      - librt==0.6.3
      - lightgbm==4.6.0
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mistune==3.1.4
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - mypy==1.19.0
      - mypy-extensions==1.1.0
      - notebook==7.5.0
      - numpy==2.3.5
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pytest-runner==6.0.1
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - pytokens==0.3.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - sci-kit==0.1.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - smmap==5.0.2
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.4
      - starlette==0.50.0
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - types-requests==2.32.4.20250913
      - types-tqdm==4.67.0.20250809
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - uvicorn==0.38.0
      - waitress==3.0.2
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - xgboost==3.1.2
prefix: C:\Users\dhila\anaconda3\envs\3DModel
